name: Generate doc and deploy to gh pages

on:
  push:
    branches:
      main
      
jobs:
  - uses: actions/checkout@v2
  - uses: mattnotmitt/doxygen-action@v1.1.0
    with:
      working-directory: 'doc/full/'
      doxyfile-path: '../../src/RFF/Doxyfile'
  - uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: doc/full