name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install packages
      run: sudo apt install -y meson libboost-all-dev ninja-build
    - name: Checkout
      uses: actions/checkout@v1
    - name: Meson Build
      run: meson build
    - name: Meson Configure
      run: meson configure -Dfreertos:allocator="" build
    - name: Ninja build
      run: cd build && ninja
    - name: Meson Test
      run: cd build && meson test
